[N,D] = size(data_train);
% create data subsets WITH replacement
frac = 1 - 1/exp(1); % Bootstrap sampling fraction: 1 - 1/e (63.2%)
[labels,~] = unique(data_train(:,end));
bag={};
for i=1:4
    idx = randsample(N,ceil(N*frac),1); % A new training set for each tree is generated by random sampling from dataset WITH replacement.
    prior = histc(data_train(idx,end),labels)/length(idx); % prob of data in each class in this subset
    uni_frac = length(unique(idx))/length(idx); % unique fraction in this subset
    bag{i} = data_train(idx,:); % store in bag
    subplot(2,2,i);
    plot_toydata(bag{i}) 
    title(sprintf('%2.2f%% Distinct Samples', uni_frac*100));
end